name: Deploy

on:
  push:
    branches:
      - master

jobs:
  push_to_registry_and_deploy:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
        - name: Check out the repo
          uses: actions/checkout@v3

        - name: Log in to Docker Hub
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
          with:
              images: dash6/suits_app.back

        - name: Build and push Docker image
          uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
          with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}

        - name: Deploy Stack
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.VPS_SSH_HOST }}
            username: ${{ secrets.VPS_SSH_USERNAME }}
            key: ${{ secrets.key }}
            script: |
                cd /root/backend
                docker stop ${{ secrets.CONTAINER_NAME }} || true
                docker container rm ${{ secrets.CONTAINER_NAME }} || true
                docker image rm -f ${{ secrets.IMAGE_NAME }} || true
                docker run -d --name backend --publish 8000:8000 dash6/suits_app.back:master
                docker exec backend npm run migrations:run --no-interaction